In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv('customer.csv')

In [ ]:
df.drop(columns=['gender', 'age'], inplace=True)

In [ ]:
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [ ]:
df['purchased'].unique()

array(['No', 'Yes'], dtype=object)

In [ ]:
X = df.iloc[:,:2]
y = df.iloc[:,-1]
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
le = LabelEncoder()
y_train_transformed = le.fit_transform(y_train)
y_test_transformed = le.transform(y_test)

In [ ]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [ ]:
y_train

2      No
6      No
40     No
37    Yes
11    Yes
49     No
45    Yes
1      No
47    Yes
23     No
38     No
15     No
28     No
24    Yes
30     No
25     No
0      No
48    Yes
29    Yes
27     No
32    Yes
35    Yes
17    Yes
7     Yes
22    Yes
42    Yes
31    Yes
12     No
8      No
3      No
34     No
26     No
19    Yes
33    Yes
21     No
41    Yes
20    Yes
10    Yes
43     No
18     No
Name: purchased, dtype: object

In [ ]:
y_train.shape

(40,)

In [ ]:
y_train_transformed

array([0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0])

In [ ]:
le.inverse_transform(np.array([0,0,0,1,0]))

array(['No', 'No', 'No', 'Yes', 'No'], dtype=object)